name: dart_sample
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/bartekpacia/dart-vm-service-extensions

environment:
  sdk: ^3.0.0

dependencies:
  vm_service: ^11.7.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2

executables:
  printer: printer
  spy: spy
