name: dart_sample
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/bartekpacia/dart-vm-service-extensions

environment:
  sdk: ^3.3.0

dependencies:
  vm_service: ^14.1.0

dev_dependencies:
  lints: ^3.0.0

executables:
  printer: printer
  spy: spy
